.env_docker: &env_docker
  image: docker:18.09.7

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind

stages:
  - tests
  - build
  - build_docker
  - rancher

variables:
  K8S_SECRETS: "purple-bots"
  K8S_SECRETS_REGISTRY: "registry-toliak-ru"
  RANCHER_URL: "https://rancher.int.toliak.ru"
  REGISTRY_URL: "registry.toliak.ru"
  DOCKER_IMAGE: "purple-bots:$CI_COMMIT_SHORT_SHA"
  RANCHER_DEPLOYMENT: "purple-bots"


test:
  image: python:3.7.8-slim-stretch

  services:
    - postgres:12.2-alpine

  variables:
    POSTGRES_DB: db_name
    POSTGRES_USER: username
    POSTGRES_PASSWORD: password
    POSTGRES_HOST_AUTH_METHOD: trust

  stage: tests

  before_script:
    - apt-get update -y
    - apt-get install -y gcc libpq-dev python3-dev gettext
    - pip install -r requirements.txt
    - |
      cd myproject/config &&
      mv .env.sample .env &&
      cd ../..

  script:
    - mkdir -p static
    - mkdir -p media/temp
    - ./scripts/run-tests.sh


build_docker:
  <<: *env_docker

  stage: build_docker
  only:
    - develop
    - /^release\/.*$/
    - master

  script:
    - docker login ${REGISTRY_URL} --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
    - docker build . -t ${REGISTRY_URL}/${DOCKER_IMAGE}
    - docker push ${REGISTRY_URL}/${DOCKER_IMAGE}


rancher:
  image: jonaskello/rancher-cli-k8s:v2.0.4

  when: manual
  stage: rancher
  only:
    - master

  script:
    - /bin/sh scripts/rancher-patch.sh

rancher_celery:
  image: jonaskello/rancher-cli-k8s:v2.0.4
  variables:
    RANCHER_DEPLOYMENT: "${CI_PROJECT_NAME}-celery"

  when: manual
  stage: rancher
  only:
    - master

  script:
    - /bin/sh scripts/rancher-patch.sh

rancher_celery_beat:
  image: jonaskello/rancher-cli-k8s:v2.0.4
  variables:
    RANCHER_DEPLOYMENT: "${CI_PROJECT_NAME}-celery-beat"

  when: manual
  stage: rancher
  only:
    - master

  script:
    - /bin/sh scripts/rancher-patch.sh


rancher_migrate:
  image: jonaskello/rancher-cli-k8s:v2.0.4

  when: manual
  stage: rancher
  only:
    - master

  script:
    - /bin/sh scripts/rancher-migrate.sh
