.env_docker: &env_docker
  image: docker:18.09.7

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  services:
    - docker:18.09.7-dind

stages:
  - tests
  - build
  - build_docker
  - rancher

variables:
  K8S_SECRETS: "my-project"
  K8S_SECRETS_REGISTRY: "my-registry"
  RANCHER_URL: "https://rancher.example.com"
  REGISTRY_URL: "registry.example.com"
  DOCKER_IMAGE: "myproject-backend"


test:
  image: python:3.7.8-slim-stretch

  services:
    - postgres:12.2-alpine

  variables:
    POSTGRES_DB: myproject
    POSTGRES_USER: myproject
    POSTGRES_PASSWORD: myproject
    POSTGRES_HOST_AUTH_METHOD: trust
    APP_DEBUG: "True"
    SECRET_KEY: "top secret key"
    DB_DRIVER: "django.db.backends.postgresql_psycopg2"
    DB_USERNAME: myproject
    DB_PASSWORD: myproject
    DB_NAME: myproject
    DB_HOST: postgres
    EMAIL_HOST: "smtp.yandex.ru"
    EMAIL_HOST_USER: "user@domain.com"
    EMAIL_HOST_PASSWORD: "password"
    EMAIL_USE_TLS: "True"
    EMAIL_TO: "[\"test@test.test\"]"
    CELERY_BROKER_URL: ""
    PE_TOKEN: ""
    AWS_ACCESS_KEY: "access-key"
    AWS_SECRET_KEY: "secret-key"
    AWS_BUCKET_NAME: "bucket-name"
    AWS_ENDPOINT_URL: "https://s3-domain.com"

  stage: tests

  before_script:
    - apt-get update -y
    - apt-get install -y gcc libpq-dev python3-dev gettext
    - pip install -r requirements.txt

  script:
    - mkdir -p static
    - mkdir -p media/temp
    - ./scripts/run-tests.sh


build_docker:
  <<: *env_docker

  stage: build_docker
  only:
    - develop
    - /^release\/.*$/
    - master

  script:
    - docker login ${REGISTRY_URL} --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
    - docker build . -t ${REGISTRY_URL}/${DOCKER_IMAGE}
    - docker push ${REGISTRY_URL}/${DOCKER_IMAGE}


rancher:
  image: jonaskello/rancher-cli-k8s:v2.0.4
  
  when: manual
  stage: rancher
  only:
    - master

  script:
    - /bin/sh scripts/rancher-patch.sh


rancher_migrate:
  image: jonaskello/rancher-cli-k8s:v2.0.4
  
  when: manual
  stage: rancher
  only:
    - master

  script:
    - /bin/sh scripts/rancher-migrate.sh
