# Generated by Django 3.1.7 on 2021-04-07 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('item_type', models.CharField(choices=[('FG', 'Something')], default='FG', max_length=2, verbose_name='Item category')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('description', models.TextField(verbose_name='Brief description')),
                ('weight', models.FloatField(blank=True, default=None, null=True, verbose_name='Weight, kg')),
                ('material', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('image', stdimage.models.StdImageField(upload_to='itemImages', verbose_name='Image')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catalogitem', verbose_name='Catalog item')),
            ],
            options={
                'verbose_name': 'Catalog. Image',
                'verbose_name_plural': 'Catalog. Images',
            },
        ),
    ]
