# Generated by Django 3.1.7 on 2021-04-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'verbose_name': 'Catalog. Item', 'verbose_name_plural': 'Catalog. Items'},
        ),
    ]
